export const CATEGORY_ACTION_TYPES= {
    FETCH_CATEGORY_START:"categor/FETCH_CATEGORY_START",
    FETCH_CATEGORY_SUCCESS:"category/FETCH_CATEGORY_SUCCESS",
    FETCH_CATEGORY_FAILIURE:"category/FETCH_CATEGORY_FAILIURE",
}